import { useContext } from "react"
import { ContextoGlobal } from "../Context/ContextoGlobal"

const CallContext = () => {
    const { buscarpeliculas,
            setBuscarPeliculas,
            vista1,
            setVista1,
            vista2,
            setVista2,
            vista3,
            setVista3,
            peliculasSoon,
            peliculas2,
            mostRanted,
            tvRanted,
            setTvRanted,
            upcomingmovies,
            setUpcomingmovies,
            arregleAllMovies,
            setArregleAllMovies,
            arreglogenres,
            setArreglogenres,
            PaginaMovies,
            setPaginaMovies,
            seriesTv,
            setSeriesTv,
            paginaseries,
            setPaginaseries,
            urlTVRanted,
            searchmovies1,
            setSearchmovies1,
            searchmovies2,
            setSearchmovies2,
            searchmovies3,
            setSearchmovies3,
            stade2,
            setStade2,
            searchtv,setSearchtv,
            searchtv2,setSearchtv2,
            actores,setActores,
            pageActor,setPageActor,
            video,setVideo,
            viewvideo,setViewvideo
            } = useContext(ContextoGlobal);
      const ShowResults = ()=>{
                setStade2(!stade2);}
  return {buscarpeliculas,
          setBuscarPeliculas,
          vista1,
          setVista1,
          vista2,
          setVista2,
          vista3,
          setVista3,
          peliculasSoon,
          peliculas2,
          mostRanted,
          tvRanted,
          setTvRanted,
          upcomingmovies,
          setUpcomingmovies,
          arregleAllMovies,
          setArregleAllMovies,
          arreglogenres,
          setArreglogenres,
          PaginaMovies,
          setPaginaMovies,
          seriesTv,
          setSeriesTv,
          paginaseries,
          setPaginaseries,
          urlTVRanted,
          searchmovies1,
          setSearchmovies1,
          searchmovies2,
          setSearchmovies2,
          searchmovies3,
          setSearchmovies3,
          stade2,
          ShowResults,
          searchtv,setSearchtv,
          searchtv2,setSearchtv2,
          actores,setActores,
          pageActor,setPageActor,
          video,setVideo,
          viewvideo,setViewvideo}
}

export default CallContext 
